name: Tests

on:
  push:
    branches: [ main, dev/*, feature/* ]
    paths:
      - 'streamlit_app_v2/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'streamlit_app_v2/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: streamlit_app_v2
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-watch
        
    - name: Install Playwright
      run: |
        pip install playwright
        playwright install chromium
        playwright install-deps
    
    - name: Run unit tests
      run: |
        pytest tests/ --ignore=tests/ui/test_streamlit_ui.py -v --cov=. --cov-report=xml
    
    - name: Run UI tests
      run: |
        # Start streamlit in background
        streamlit run APE.py --server.port 8501 --server.headless true &
        
        # Wait for server to start
        sleep 10
        
        # Run UI tests
        pytest tests/ui/test_streamlit_ui.py -v
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./streamlit_app_v2/coverage.xml
        flags: unittests
        name: codecov-umbrella