[theme]
# Option 3: Softer Contrast
primaryColor = "#7DE1DF"  # Teal to match Carbon button highlight
backgroundColor = "#FFFFFF"  # Pure white background
secondaryBackgroundColor = "#F4F4F4"  # Very light gray (Carbon gray 10)
textColor = "#161616"  # Very dark gray (Carbon gray 100)
font = "sans serif"

[server]
# Don't specify port - let Streamlit Cloud choose
enableCORS = true  # Changed to true to be compatible with XSRF protection
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[runner]
fastReruns = true

# Removed deprecated option: showPyplotGlobalUse